### PR TITLE
Refactor and updates

### PR DESCRIPTION
**Pull request by ryan-cahill**
## Overview
Closes https://gitlab.com/architect-io/product/-/issues/268

## Changes
* Updated starter project with new standards
* Updated Dockerfiles
* Added new DB service to component

## Pictures
`architect dev`
image

`architect dev --debug=false`
image

`architect deploy nextjs -e example-environment --auto-approve`
image

## TODO List
Before merging, a PR will need
- [x] Signoff from product if there are UX changes 
- [x] Signoff from one other engineer at Architect.io

### CODE REVIEW

**Comment by TylerAldrich** [comment]
@ryan-cahill I'm getting an error when running this with `--debug=false`:


```
 => => writing image sha256:6c0ced5cae0474cb9e3722165e2cd80dd7549ffbf642374a412b968c60bbb851                                0.0s
 => => naming to docker.io/library/nextjs--app                                                                              0.0s
Building containers... done

Once the containers are running they will be accessible via the following urls:
https://app.localhost.architect.sh:443/ => nextjs--app

http://localhost:443/ => gateway:443
http://localhost:8080/ => gateway:8080
http://localhost:50000/ => nextjs--app:3000
http://localhost:50001/ => nextjs--database:5432

Starting containers...

nextjs--database-1  |
nextjs--database-1  |  PostgreSQL Database directory appears to contain a database; Skipping initialization
nextjs--database-1  |
gateway-1           |  time="2023-03-21T20:40:01Z" level=info msg="Configuration loaded from flags."
nextjs--app-1       |  Prisma schema loaded from prisma/schema.prisma
nextjs--app-1       |  Datasource "db": PostgreSQL database "default_db", schema "public" at "nextjs--database:5432"
nextjs--app-1       |
nextjs--app-1       |  1 migration found in prisma/migrations
nextjs--app-1       |
ERROR: nextjs.services.app has encountered an error and is being restarted.
d0e9c6f011bc21e5aa8ab4eda79fb97cbae25434585442bc5769ad24cbc41d95
nextjs--app-1       |  Prisma schema loaded from prisma/schema.prisma
nextjs--app-1       |  Datasource "db": PostgreSQL database "default_db", schema "public" at "nextjs--database:5432"
nextjs--app-1       |
nextjs--app-1       |  1 migration found in prisma/migrations
nextjs--app-1       |
ERROR: nextjs.services.app has encountered an error and is being restarted.
d0e9c6f011bc21e5aa8ab4eda79fb97cbae25434585442bc5769ad24cbc41d95
```

**Comment by TylerAldrich** [comment]
Update - I couldn't actually reproduce this... I think everything in this PR looks fine, we should see if @Zach-at-Arch or somebody else runs into this issue but things seem to be working just fine now

**Review by TylerAldrich — APPROVED** [review]
Approved with the caveat that I did hit a weird error that I couldn't reproduce mentioned in other comments 😛

**Review by zach-j-dev — APPROVED** [review]
Good on product side. @TylerAldrich , I wasn't able to re-create the issue you had

**Pull request merged**
